version: 2
jobs:
  build:

    working_directory: ~/middleware-starfish

    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - run: mvn test
        
      - store_test_results:
          path: target/surefire-reports
