version: 2
jobs:
  build:

    working_directory: ~/middleware-starfish

    docker:
    - image: circleci/openjdk:8u171-jdk

    steps:

      - checkout

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
          - ~/.m2
          key: middleware-starfish-{{ checksum "pom.xml" }}

      - run: mvn test

      - store_test_results:
          path: target/surefire-reports
