version: 2
jobs:
  build:

    working_directory: ~/middleware-starfish

    docker:
    - image: circleci/openjdk:8-jdk-browsers
    - image: circleci/postgres:9.6.3-alpine
      environment:
        POSTGRES_USER: starfish
        POSTGRES_DB: starfish

    steps:

    - checkout

    - restore_cache:
        key: middleware-starfish-{{ checksum "pom.xml" }}

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: middleware-starfish-{{ checksum "pom.xml" }}

    - run: mvn package

    - store_test_results:
        path: target/surefire-reports

    - store_artifacts:
        path: target/middleware-starfish-0.0.1-SNAPSHOT.jar