CREATE TABLE SF_AUTHORITY (
    ID BIGINT,
    NAME VARCHAR(80),
    CONSTRAINT PK_SF_AUTHORITY PRIMARY KEY (id)
);

CREATE TABLE SF_SECTION (
  ID BIGINT,
  NAME VARCHAR(255) NOT NULL,
  CONSTRAINT PK_SF_SECTION PRIMARY KEY (ID)
);

CREATE TABLE SF_CARD_STATUS (
    ID BIGINT,
    NAME VARCHAR (80),
    CONSTRAINT PK_SF_CARD_STATUS PRIMARY KEY (ID)
);

CREATE TABLE SF_ROLE (
    ID BIGINT,
    NAME VARCHAR (80),
    CONSTRAINT PK_SF_ROLE PRIMARY KEY (ID)
);

CREATE TABLE SF_SQUAD (
  ID BIGINT,
  NAME VARCHAR(255) NOT NULL,
  CONSTRAINT PK_SF_SQUAD PRIMARY KEY (id)
);

CREATE TABLE SF_USER (
    ID BIGINT,
    ACTIVE BOOLEAN,
    PASSWORD VARCHAR(64),
    NAME VARCHAR(80) NOT NULL,
    SALT VARCHAR(80),
    CONSTRAINT PK_SF_USER PRIMARY KEY (ID)
);

CREATE TABLE SF_CARD (
    ID BIGINT,
    DESCRIPTION VARCHAR(3500),
    SECTION_ID BIGINT,
    SQUAD_ID BIGINT,
    STATUS_ID BIGINT,
    USER_ID BIGINT,
    CONSTRAINT PK_SF_CARD PRIMARY KEY (ID),
    CONSTRAINT PF_SF_CARD__SF_SECTION FOREIGN KEY (SECTION_ID)
        REFERENCES SF_SECTION (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT PF_SF_CARD__SF_CARD_STATUS FOREIGN KEY (STATUS_ID)
        REFERENCES SF_CARD_STATUS (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT PF_SF_CARD__SF_SQUAD FOREIGN KEY (SQUAD_ID)
        REFERENCES SF_SQUAD (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT PF_SF_CARD__SF_USER FOREIGN KEY (USER_ID)
        REFERENCES SF_USER (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE SF_ROLE_AUTHORITY (
    ROLE_ID BIGINT NOT NULL,
    AUTHORITY_ID BIGINT NOT NULL,
    CONSTRAINT PK_SF_ROLE_AUTHORITY PRIMARY KEY (ROLE_ID, AUTHORITY_ID),
    CONSTRAINT FK_SF_ROLE_AUTHORITY__SF_AUTHORITY FOREIGN KEY (AUTHORITY_ID)
        REFERENCES SF_AUTHORITY (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_SF_ROLE_AUTHORITY__SF_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES SF_ROLE (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE SF_USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT PK_SF_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_SF_USER_ROLE__SF_USER FOREIGN KEY (USER_ID)
        REFERENCES SF_USER (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_SF_USER_ROLE__SF_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES SF_ROLE (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


CREATE TABLE SF_USER_SQUAD (
    USER_ID BIGINT NOT NULL,
    SQUAD_ID BIGINT NOT NULL,
    CONSTRAINT PK_SF_USER_SQUAD PRIMARY KEY (USER_ID, SQUAD_ID),
    CONSTRAINT FK_SF_USER_SQUAD__SF_USER FOREIGN KEY (USER_ID)
        REFERENCES SF_USER (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_SF_USER_SQUAD__SF_SQUAD FOREIGN KEY (SQUAD_ID)
        REFERENCES SF_SQUAD (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

INSERT INTO SF_AUTHORITY (ID, NAME) VALUES
  (0, 'READ_SQUAD'),
  (1, 'CREATE_SQUAD'),
  (2, 'DELETE_SQUAD'),
  (3, 'UPDATE_SQUAD'),
  (4, 'READ_CARD'),
  (6, 'CREATE_CARD'),
  (5, 'DELETE_CARD'),
  (7, 'UPDATE_CARD');

INSERT INTO SF_SECTION (ID, NAME) VALUES
  (0, 'Keep Doing'),
  (1, 'Start Doing'),
  (2, 'Stop doing'),
  (3, 'More of'),
  (4, 'Less of');

INSERT INTO SF_SQUAD (ID, NAME) VALUES
  (0, 'Bug Busters'),
  (1, 'Game of Threads');

CREATE SEQUENCE SQ_SF_USER_ID START 1;
CREATE SEQUENCE SQ_SF_CARD_ID START 1;
CREATE SEQUENCE SQ_SF_CARD_STATUS_ID START 1;
CREATE SEQUENCE SQ_SF_ROLE_ID START 1;
CREATE SEQUENCE SQ_SF_SECTION_ID START 1;
CREATE SEQUENCE SQ_SF_SQUAD_ID START 1;
CREATE SEQUENCE SQ_SF_AUTHORITY_ID START 1;
