CREATE TABLE SF_AUTHORITY (
    ID BIGINT NOT NULL,
    NAME VARCHAR(80),
    CONSTRAINT PK_SF_AUTHORITY PRIMARY KEY (id)
);

INSERT INTO SF_AUTHORITY (ID, NAME) VALUES
  (0, "READ_SQUAD"),
  (1, "CREATE_SQUAD"),
  (2, "DELETE_SQUAD"),
  (3, "UPDATE_SQUAD"),
  (4, "READ_CARD"),
  (6, "CREATE_CARD"),
  (5, "DELETE_CARD"),
  (7, "UPDATE_CARD");
