CREATE TABLE SF_ROLE_AUTHORITY
(
    ROLE_ID BIGINT NOT NULL,
    AUTHORITY_ID BIGINT NOT NULL,
    CONSTRAINT PK_SF_ROLE_AUTHORITY PRIMARY KEY (ROLE_ID, AUTHORITY_ID),
    CONSTRAINT FK_SF_ROLE_AUTHORITY__SF_AUTHORITY FOREIGN KEY (AUTHORITY_ID)
        REFERENCES SF_AUTHORITY (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_SF_ROLE_AUTHORITY__SF_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES SF_ROLE (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


