CREATE TABLE SF_SQUAD (
  ID INT IDENTITY,
  NAME VARCHAR(255) NOT NULL,
  CONSTRAINT PK_SF_SQUAD PRIMARY KEY (id)
);

INSERT INTO SF_SQUAD (ID, NAME) VALUES
  (0, "Bug Busters"),
  (1, "Game of Threads");

