CREATE TABLE SF_USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT PK_SF_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_SF_USER_ROLE__SF_USER FOREIGN KEY (USER_ID)
        REFERENCES SF_USER (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_SF_USER_ROLE__SF_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES SF_ROLE (ID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
